import Foundation

public enum IOSUseElementTypes {
    public static func displayName(canonicalName: String) -> String {
        switch canonicalName {
        case "Application": return "App"
        case "StaticText": return "Text"
        case "TextField", "SearchField": return "Input"
        case "SecureTextField": return "SecureInput"
        case "PageIndicator": return "Page"
        case "ScrollView": return "Scroll"
        case "CollectionView": return "Collection"
        case "WebView": return "Web"
        case "Other": return "-"
        default: return canonicalName
        }
    }

    public static func displayName(rawType: Int32) -> String {
        displayName(canonicalName: canonicalName(rawType: rawType))
    }

    public static func canonicalName(rawType: Int32) -> String {
        switch rawType {
        case 0: return "Any"
        case 1: return "Other"
        case 2: return "Application"
        case 3: return "Group"
        case 4: return "Window"
        case 5: return "Sheet"
        case 6: return "Drawer"
        case 7: return "Alert"
        case 8: return "Dialog"
        case 9: return "Button"
        case 10: return "RadioButton"
        case 11: return "RadioGroup"
        case 12: return "CheckBox"
        case 13: return "DisclosureTriangle"
        case 14: return "PopUpButton"
        case 15: return "ComboBox"
        case 16: return "MenuButton"
        case 17: return "ToolbarButton"
        case 18: return "Popover"
        case 19: return "Keyboard"
        case 20: return "Key"
        case 21: return "NavigationBar"
        case 22: return "TabBar"
        case 23: return "TabGroup"
        case 24: return "Toolbar"
        case 25: return "StatusBar"
        case 26: return "Table"
        case 27: return "TableRow"
        case 28: return "TableColumn"
        case 29: return "Outline"
        case 30: return "OutlineRow"
        case 31: return "Browser"
        case 32: return "CollectionView"
        case 33: return "Slider"
        case 34: return "PageIndicator"
        case 35: return "ProgressIndicator"
        case 36: return "ActivityIndicator"
        case 37: return "SegmentedControl"
        case 38: return "Picker"
        case 39: return "PickerWheel"
        case 40: return "Switch"
        case 41: return "Toggle"
        case 42: return "Link"
        case 43: return "Image"
        case 44: return "Icon"
        case 45: return "SearchField"
        case 46: return "ScrollView"
        case 47: return "ScrollBar"
        case 48: return "StaticText"
        case 49: return "TextField"
        case 50: return "SecureTextField"
        case 51: return "DatePicker"
        case 52: return "TextView"
        case 53: return "Menu"
        case 54: return "MenuItem"
        case 55: return "MenuBar"
        case 56: return "MenuBarItem"
        case 57: return "Map"
        case 58: return "WebView"
        case 59: return "IncrementArrow"
        case 60: return "DecrementArrow"
        case 61: return "Timeline"
        case 62: return "RatingIndicator"
        case 63: return "ValueIndicator"
        case 64: return "SplitGroup"
        case 65: return "Splitter"
        case 66: return "RelevanceIndicator"
        case 67: return "ColorWell"
        case 68: return "HelpTag"
        case 69: return "Matte"
        case 70: return "DockItem"
        case 71: return "Ruler"
        case 72: return "RulerMarker"
        case 73: return "Grid"
        case 74: return "LevelIndicator"
        case 75: return "Cell"
        case 76: return "LayoutArea"
        case 77: return "LayoutItem"
        case 78: return "Handle"
        case 79: return "Stepper"
        case 80: return "Tab"
        case 81: return "TouchBar"
        case 82: return "StatusItem"
        default: return "Other"
        }
    }
}
