export const hostBridgeCaseMetadata = [
  { id: 'OL-2', group: 'host-bridge', kind: 'oslog', setup: 'simulator target', assertion: 'stdout contains cleared count', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-1', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-3', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'filtered oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-4', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'regex flag oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-5', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'custom-name oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-6', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'bundle-filter oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-7', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'global oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-8', group: 'host-bridge', kind: 'oslog', setup: 'simulator target', assertion: 'stdout contains cleared count', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-9', group: 'host-bridge', kind: 'oslog-file', setup: 'simulator target', assertion: 'timeout oslog artifact exists', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'NSL-3', group: 'host-bridge', kind: 'nslog-error', setup: 'none', assertion: 'legacy grep usage fails with read guidance', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'NSL-4', group: 'host-bridge', kind: 'nslog-error', setup: 'none', assertion: 'read without capture fails with start guidance', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'CFG-2', group: 'host-bridge', kind: 'unsupported', setup: 'real device signing', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'CFG-3', group: 'host-bridge', kind: 'unsupported', setup: 'Apple ID login', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'STOP-1R', group: 'host-bridge', kind: 'unsupported', setup: 'real device lifecycle', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'DOM-9', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-5A', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-5C', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-5D', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-6B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-6C', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-6D', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-6E', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-11B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'FIND-13', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'SW-9B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'SW-16', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-12', group: 'host-bridge', kind: 'dom-presentation', setup: 'settings home', assertion: 'presentation shape has app, direction and rects', coverage: 'simulator' },
  { id: 'PROXY-1', group: 'host-bridge', kind: 'proxy-doctor', setup: 'none', assertion: 'doctor reports LAN IP and not running without SSID', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'PROXY-2', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-3', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-4', group: 'host-bridge', kind: 'bridge-static-check', setup: 'none', assertion: 'bridged to Swift CLI unit tests plus no probe references', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-5', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-5B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-7', group: 'host-bridge', kind: 'proxy-error', setup: 'no last capture', assertion: 'proxy read asks to start proxy', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'STOP-1', group: 'host-bridge', kind: 'stop', setup: 'active driver lock', assertion: 'stop removes driver.lock and preserves legacy session', coverage: 'simulator' },
  { id: 'STOP-2', group: 'host-bridge', kind: 'stop-error', setup: 'no active driver lock', assertion: 'stop reports No active driver', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'STOP-3', group: 'host-bridge', kind: 'unsupported', setup: 'unit-only terminator failure', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'IN-7', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'OL-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'OL-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-1', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-2', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-5', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-7', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-8', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-9', group: 'host-bridge', kind: 'unsupported', setup: 'real app with NSLogger', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
];

export function buildHostBridgeCases(ctx) {
  const {
    iosHome,
    path,
    runCaseContains,
    runCaseFailsContains,
    runCaseFileExists,
    runDriverBridgeCase,
    runDomPresentationCase,
    runProxyDoctorCase,
    runProxyReadMissingCaptureCase,
    runStopClearsDriverLockCase,
    runStopWithoutDriverLockCase,
    runSwiftBridgeCase,
    sim,
    unsupportedCase,
  } = ctx;

  return [
    { id: 'OL-2', run: () => runCaseContains('OL-2', 'cleared=', ['oslog', '--clear', '--udid', sim.udid]) },
    { id: 'OL-1', run: () => runCaseFileExists('OL-1', path.join(iosHome, 'artifacts/oslog.log'), ['oslog', '--name', 'oslog', '--udid', sim.udid]) },
    { id: 'OL-3', run: () => runCaseFileExists('OL-3', path.join(iosHome, 'artifacts/oslog-pattern.log'), ['oslog', '--name', 'oslog-pattern', '--pattern', '__ios_use_no_such_log_line__', '--udid', sim.udid]) },
    { id: 'OL-4', run: () => runCaseFileExists('OL-4', path.join(iosHome, 'artifacts/oslog-flags.log'), ['oslog', '--name', 'oslog-flags', '--pattern', '__IOS_USE_NO_SUCH_LOG_LINE__', '--flags', 'i', '--udid', sim.udid]) },
    { id: 'OL-5', run: () => runCaseFileExists('OL-5', path.join(iosHome, 'artifacts/custom-oslog-name.log'), ['oslog', '--name', 'custom-oslog-name', '--udid', sim.udid]) },
    { id: 'OL-6', run: () => runCaseFileExists('OL-6', path.join(iosHome, 'artifacts/oslog-bundle.log'), ['oslog', '--name', 'oslog-bundle', '--bundle-id', 'com.apple.Preferences', '--udid', sim.udid]) },
    { id: 'OL-7', run: () => runCaseFileExists('OL-7', path.join(iosHome, 'artifacts/oslog-global.log'), ['oslog', '--name', 'oslog-global', '--udid', sim.udid]) },
    { id: 'OL-8', run: () => runCaseContains('OL-8', 'cleared=', ['oslog', '--clear', '--bundle-id', 'com.apple.Preferences', '--udid', sim.udid]) },
    { id: 'OL-9', run: () => runCaseFileExists('OL-9', path.join(iosHome, 'artifacts/oslog-timeout.log'), ['oslog', '--name', 'oslog-timeout', '--pattern', '__ios_use_no_such_log_line__', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'NSL-3', run: () => runCaseFailsContains('NSL-3', 'nslog read', ['nslog', '--grep', 'ready']) },
    { id: 'NSL-4', run: () => runCaseFailsContains('NSL-4', 'ios-use nslog start', ['nslog', 'read']) },
    { id: 'CFG-2', run: () => unsupportedCase('CFG-2') },
    { id: 'CFG-3', run: () => unsupportedCase('CFG-3') },
    { id: 'STOP-1R', run: () => unsupportedCase('STOP-1R') },
    ...[
      'DOM-9', 'DOM-10', 'DOM-11',
      'FIND-5A', 'FIND-5C', 'FIND-5D', 'FIND-6', 'FIND-6B', 'FIND-6C', 'FIND-6D', 'FIND-6E',
      'FIND-10', 'FIND-11', 'FIND-11B', 'FIND-13',
      'SW-9B', 'SW-16',
    ].map(id => ({ id, run: () => runDriverBridgeCase(id) })),
    { id: 'DOM-12', run: runDomPresentationCase },
    { id: 'PROXY-1', run: runProxyDoctorCase },
    ...['PROXY-2', 'PROXY-3', 'PROXY-4', 'PROXY-5', 'PROXY-5B', 'PROXY-6'].map(id => ({ id, run: () => runSwiftBridgeCase(id) })),
    { id: 'PROXY-7', run: runProxyReadMissingCaptureCase },
    { id: 'STOP-1', run: runStopClearsDriverLockCase },
    { id: 'STOP-2', run: runStopWithoutDriverLockCase },
    { id: 'STOP-3', run: () => unsupportedCase('STOP-3') },
    ...['IN-7', 'OL-10', 'OL-11', 'NSL-1', 'NSL-2', 'NSL-5', 'NSL-6', 'NSL-7', 'NSL-8', 'NSL-10'].map(id => ({ id, run: () => runSwiftBridgeCase(id) })),
    { id: 'NSL-9', run: () => unsupportedCase('NSL-9') },
  ];
}
