export const hostBridgeCaseMetadata = [
  { id: 'HELP-1', group: 'host-bridge', kind: 'help', setup: 'none', assertion: 'top-level help short-circuits and prints usage', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'HELP-2', group: 'host-bridge', kind: 'help', setup: 'none', assertion: 'selected driver command help short-circuits and prints command usage', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-2', group: 'host-bridge', kind: 'oslog-error', setup: 'simulator target', assertion: 'deprecated clear option is rejected', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-1', group: 'host-bridge', kind: 'oslog-error', setup: 'simulator target', assertion: 'zero timeout is rejected', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-3', group: 'host-bridge', kind: 'oslog-pattern', setup: 'simulator target', assertion: 'pattern timeout command succeeds', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-4', group: 'host-bridge', kind: 'oslog-flags', setup: 'simulator target', assertion: 'regex flag command succeeds', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-5', group: 'host-bridge', kind: 'oslog-process', setup: 'simulator target', assertion: 'process filter command succeeds', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-6', group: 'host-bridge', kind: 'oslog-pid', setup: 'simulator target', assertion: 'pid filter command succeeds', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-7', group: 'host-bridge', kind: 'oslog', setup: 'simulator target', assertion: 'global timeout command succeeds', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-8', group: 'host-bridge', kind: 'oslog-error', setup: 'simulator target', assertion: 'legacy bundle filter is rejected', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'OL-9', group: 'host-bridge', kind: 'oslog-error', setup: 'simulator target', assertion: 'artifact name option is rejected', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'NSL-3', group: 'host-bridge', kind: 'nslog-error', setup: 'none', assertion: 'legacy grep usage fails with read guidance', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'NSL-4', group: 'host-bridge', kind: 'nslog-error', setup: 'none', assertion: 'read without capture fails with start guidance', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'CFG-2', group: 'host-bridge', kind: 'unsupported', setup: 'real device signing', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'CFG-3', group: 'host-bridge', kind: 'unsupported', setup: 'Apple ID login', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'STOP-1R', group: 'host-bridge', kind: 'unsupported', setup: 'real device lifecycle', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'DOM-9', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-5A', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-5C', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-5D', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-6B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-6C', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-6D', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-11B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'RAWFIND-13', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'SW-9B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'SW-16', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to driver unit tests', coverage: 'driver-unit', requiresPrerequisite: false },
  { id: 'DOM-12', group: 'host-bridge', kind: 'dom-presentation', setup: 'settings home', assertion: 'presentation shape has app, direction and rects', coverage: 'simulator' },
  { id: 'PROXY-1', group: 'host-bridge', kind: 'proxy-doctor', setup: 'none', assertion: 'doctor reports LAN IP and not running without SSID', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'PROXY-2', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-3', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-4', group: 'host-bridge', kind: 'bridge-static-check', setup: 'none', assertion: 'bridged to Swift CLI unit tests plus no probe references', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-5', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-5B', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'PROXY-7', group: 'host-bridge', kind: 'proxy-error', setup: 'no last capture', assertion: 'proxy read asks to start proxy', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'STOP-1', group: 'host-bridge', kind: 'stop', setup: 'active driver lock', assertion: 'stop removes driver.lock and preserves legacy session', coverage: 'simulator' },
  { id: 'STOP-2', group: 'host-bridge', kind: 'stop-error', setup: 'no active driver lock', assertion: 'stop reports No active driver', coverage: 'simulator', requiresPrerequisite: false },
  { id: 'STOP-3', group: 'host-bridge', kind: 'unsupported', setup: 'unit-only terminator failure', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
  { id: 'IN-7', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'OL-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'OL-11', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-1', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-2', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-5', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-6', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-7', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-8', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-10', group: 'host-bridge', kind: 'bridge', setup: 'none', assertion: 'bridged to Swift CLI unit tests', coverage: 'swift-cli-unit', requiresPrerequisite: false },
  { id: 'NSL-9', group: 'host-bridge', kind: 'unsupported', setup: 'real app with NSLogger', assertion: 'unsupported by simulator runner', coverage: 'unsupported', requiresPrerequisite: false },
];

export function buildHostBridgeCases(ctx) {
  const {
    artifactDir,
    path,
    recordFail,
    recordPass,
    recordSkip,
    runCase,
    runCaseContains,
    runCaseFailsContains,
    runDriverBridgeCase,
    runDomPresentationCase,
    runProxyDoctorCase,
    runProxyReadMissingCaptureCase,
    runStopClearsDriverLockCase,
    runStopWithoutDriverLockCase,
    runSwiftBridgeCase,
    runCliToFiles,
    selected,
    sim,
    unsupportedCase,
  } = ctx;

  return [
    { id: 'HELP-1', run: () => runCaseContains('HELP-1', 'Usage: ios-use [--help] [--version] <command>', ['--help']) },
    { id: 'HELP-2', run: () => {
      if (!selected('HELP-2')) return recordSkip('HELP-2');
      console.log('[sim-test] RUN HELP-2: ios-use dom/input --help');
      const dom = runCliToFiles(['dom', '--help'], path.join(artifactDir, 'HELP-2-dom.out'), path.join(artifactDir, 'HELP-2-dom.err'));
      const input = runCliToFiles(['input', '--help'], path.join(artifactDir, 'HELP-2-input.out'), path.join(artifactDir, 'HELP-2-input.err'));
      const output = `${dom.stdout}${dom.stderr}${input.stdout}${input.stderr}`;
      if (
        dom.code === 0
        && input.code === 0
        && dom.stdout.includes('Usage: ios-use dom')
        && input.stdout.includes('Usage: ios-use input')
      ) recordPass('HELP-2');
      else recordFail('HELP-2', output, dom.code === 0 && input.code === 0 ? 'assertion' : 'command');
    } },
    { id: 'OL-2', run: () => runCaseFailsContains('OL-2', 'unknown option', ['oslog', '--clear', '--udid', sim.udid]) },
    { id: 'OL-1', run: () => runCaseFailsContains('OL-1', '--timeout must be greater than 0', ['oslog', '--timeout', '0', '--udid', sim.udid]) },
    { id: 'OL-3', run: () => runCase('OL-3', ['oslog', '--pattern', '__ios_use_no_such_log_line__', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'OL-4', run: () => runCase('OL-4', ['oslog', '--pattern', '__IOS_USE_NO_SUCH_LOG_LINE__', '--flags', 'i', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'OL-5', run: () => runCase('OL-5', ['oslog', '--process', 'Preferences', '--pattern', '__ios_use_no_such_log_line__', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'OL-6', run: () => runCase('OL-6', ['oslog', '--pid', '0', '--pattern', '__ios_use_no_such_log_line__', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'OL-7', run: () => runCase('OL-7', ['oslog', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'OL-8', run: () => runCaseFailsContains('OL-8', 'unknown option', ['oslog', '--bundle-id', 'com.apple.Preferences', '--udid', sim.udid]) },
    { id: 'OL-9', run: () => runCaseFailsContains('OL-9', 'unknown option', ['oslog', '--name', 'oslog-timeout', '--pattern', '__ios_use_no_such_log_line__', '--timeout', '0.2', '--udid', sim.udid]) },
    { id: 'NSL-3', run: () => runCaseFailsContains('NSL-3', 'nslog read', ['nslog', '--grep', 'ready']) },
    { id: 'NSL-4', run: () => runCaseFailsContains('NSL-4', 'ios-use nslog start', ['nslog', 'read']) },
    { id: 'CFG-2', run: () => unsupportedCase('CFG-2') },
    { id: 'CFG-3', run: () => unsupportedCase('CFG-3') },
    { id: 'STOP-1R', run: () => unsupportedCase('STOP-1R') },
    ...[
      'DOM-9', 'DOM-10', 'DOM-11',
      'RAWFIND-5A', 'RAWFIND-5C', 'RAWFIND-5D', 'RAWFIND-6', 'RAWFIND-6B', 'RAWFIND-6C', 'RAWFIND-6D',
      'RAWFIND-10', 'RAWFIND-11', 'RAWFIND-11B', 'RAWFIND-13',
      'SW-9B', 'SW-16',
    ].map(id => ({ id, run: () => runDriverBridgeCase(id) })),
    { id: 'DOM-12', run: runDomPresentationCase },
    { id: 'PROXY-1', run: runProxyDoctorCase },
    ...['PROXY-2', 'PROXY-3', 'PROXY-4', 'PROXY-5', 'PROXY-5B', 'PROXY-6'].map(id => ({ id, run: () => runSwiftBridgeCase(id) })),
    { id: 'PROXY-7', run: runProxyReadMissingCaptureCase },
    { id: 'STOP-1', run: runStopClearsDriverLockCase },
    { id: 'STOP-2', run: runStopWithoutDriverLockCase },
    { id: 'STOP-3', run: () => unsupportedCase('STOP-3') },
    ...['IN-7', 'OL-10', 'OL-11', 'NSL-1', 'NSL-2', 'NSL-5', 'NSL-6', 'NSL-7', 'NSL-8', 'NSL-10'].map(id => ({ id, run: () => runSwiftBridgeCase(id) })),
    { id: 'NSL-9', run: () => unsupportedCase('NSL-9') },
  ];
}
