#!/bin/bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
FRIDA_COMMIT="0afeb85fcdeae1d995a55bc07f0fe57b197aecae"
FRIDA_REPOSITORY="https://github.com/frida/frida-gum.git"
ENGINE_ABI_REVISION="ios-use-frida-engine-cabi-v2"
AGENT_SHA256="$(shasum -a 256 "$ROOT_DIR/playcover-frida-engine/IOSUseFridaAgent.js" | awk '{print $1}')"
ENGINE_SOURCE_CLOSURE_SHA256="$(python3 - "$ROOT_DIR" <<'PY'
import hashlib
import os
import struct
import sys

root = sys.argv[1]
paths = sorted([
    "playcover-frida-engine/IOSUseFridaAgent.js",
    "playcover-frida-engine/IOSUseFridaEngine.h",
    "playcover-frida-engine/IOSUseFridaEngine.m",
])
hasher = hashlib.sha256()
for relative in paths:
    path = os.path.join(root, relative)
    relative_bytes = relative.encode("utf-8")
    content = open(path, "rb").read()
    hasher.update(struct.pack(">Q", len(relative_bytes)))
    hasher.update(relative_bytes)
    hasher.update(struct.pack(">Q", len(content)))
    hasher.update(content)
print(hasher.hexdigest())
PY
)"
OUTPUT="$ROOT_DIR/.ios-use/playcover/IOSUseFridaEngine.framework"
SOURCE_ROOT="${IOS_USE_FRIDA_SOURCE_ROOT:-}"
GUM_BUILD="${IOS_USE_FRIDA_GUM_BUILD:-}"
GUM_DEVKIT="${IOS_USE_FRIDA_GUM_DEVKIT:-}"
BUILD_GUM=false
REPLACE=false

usage() {
  cat <<'EOF'
Usage: scripts/build_playcover_frida_engine.sh
  [--output <IOSUseFridaEngine.framework>]
  [--source-root <pinned frida-gum checkout>]
  [--gum-build <official Catalyst Gum build directory>]
  [--gum-devkit <official generated gumjs/devkit directory>]
  [--build-gum]
  [--replace]

The Gum checkout must be exactly the pinned commit. The devkit and static
archive must be generated by the official Frida GumJS Meson build; this script
only builds the ios-use ABI wrapper and never substitutes another JS engine.
`--build-gum` runs the pinned-source Catalyst devkit build before compiling the
wrapper. Without it, pass an already generated `--gum-build` or `--gum-devkit`.
EOF
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --output)
      [ "$#" -ge 2 ] || { echo "--output requires a path" >&2; exit 64; }
      OUTPUT="$2"; shift 2 ;;
    --source-root)
      [ "$#" -ge 2 ] || { echo "--source-root requires a path" >&2; exit 64; }
      SOURCE_ROOT="$2"; shift 2 ;;
    --gum-build)
      [ "$#" -ge 2 ] || { echo "--gum-build requires a path" >&2; exit 64; }
      GUM_BUILD="$2"; shift 2 ;;
    --gum-devkit)
      [ "$#" -ge 2 ] || { echo "--gum-devkit requires a path" >&2; exit 64; }
      GUM_DEVKIT="$2"; shift 2 ;;
    --build-gum) BUILD_GUM=true; shift ;;
    --replace) REPLACE=true; shift ;;
    --help|-h) usage; exit 0 ;;
    *) echo "unknown option: $1" >&2; usage >&2; exit 64 ;;
  esac
done

if [ -z "$SOURCE_ROOT" ]; then
  cache_root="${IOS_USE_FRIDA_SOURCE_CACHE:-$HOME/Library/Caches/dev.ios-use/mac/frida-engine/source}"
  SOURCE_ROOT="$cache_root/$FRIDA_COMMIT"
  mkdir -p "$(dirname "$SOURCE_ROOT")"
  if [ ! -d "$SOURCE_ROOT/.git" ]; then
    git clone --filter=blob:none "$FRIDA_REPOSITORY" "$SOURCE_ROOT"
  fi
fi

SOURCE_ROOT="$(cd "$SOURCE_ROOT" && pwd)"
if [ -n "$(git -C "$SOURCE_ROOT" status --porcelain=v1 --untracked-files=all)" ]; then
  echo "Frida source checkout is dirty; refusing to change it before pinning $FRIDA_COMMIT" >&2
  exit 65
fi
actual_commit="$(git -C "$SOURCE_ROOT" rev-parse HEAD)"
if [ "$actual_commit" != "$FRIDA_COMMIT" ]; then
  git -C "$SOURCE_ROOT" fetch --no-tags --depth=1 origin "$FRIDA_COMMIT"
  git -C "$SOURCE_ROOT" checkout --detach "$FRIDA_COMMIT"
  actual_commit="$(git -C "$SOURCE_ROOT" rev-parse HEAD)"
fi
if [ "$actual_commit" != "$FRIDA_COMMIT" ]; then
  echo "Frida source is $actual_commit, expected pinned $FRIDA_COMMIT" >&2
  exit 65
fi
git -C "$SOURCE_ROOT" submodule update --init --recursive

if [ "$BUILD_GUM" = true ] && [ -n "$GUM_DEVKIT" ]; then
  echo "--build-gum cannot be combined with --gum-devkit" >&2
  exit 64
fi
if [ "$BUILD_GUM" = true ] && [ -n "$GUM_BUILD" ]; then
  echo "--build-gum cannot be combined with --gum-build" >&2
  exit 64
fi
if [ -z "$GUM_DEVKIT" ] && [ -n "$GUM_BUILD" ]; then
  GUM_DEVKIT="$GUM_BUILD/bindings/gumjs/devkit"
fi
if [ "$BUILD_GUM" = true ]; then
  GUM_BUILD_ROOT="${IOS_USE_FRIDA_GUM_BUILD_ROOT:-${TMPDIR:-/tmp}/ios-use-frida-gum-build}"
  case "$GUM_BUILD_ROOT" in
    /*) ;;
    *) GUM_BUILD_ROOT="$ROOT_DIR/$GUM_BUILD_ROOT" ;;
  esac
  GUM_HELPER_ARGS=(
    --source-root "$SOURCE_ROOT"
    --build-root "$GUM_BUILD_ROOT"
  )
  [ "$REPLACE" = true ] && GUM_HELPER_ARGS+=(--replace)
  bash "$ROOT_DIR/scripts/build_playcover_frida_gum_catalyst.sh" \
    "${GUM_HELPER_ARGS[@]}"
  GUM_BUILD="$GUM_BUILD_ROOT/gum-catalyst"
  GUM_DEVKIT="$GUM_BUILD/bindings/gumjs/devkit"
fi
if [ -z "$GUM_DEVKIT" ]; then
  echo "an official Catalyst GumJS devkit is required; pass --gum-build, --gum-devkit, or --build-gum" >&2
  echo "build it from the pinned checkout with Frida's Meson gumjs/devkit target" >&2
  exit 69
fi
GUM_DEVKIT="$(cd "$GUM_DEVKIT" && pwd)"
GUM_BUILD="${GUM_BUILD:-$(cd "$GUM_DEVKIT/../../.." && pwd)}"
[ -f "$GUM_DEVKIT/frida-gumjs.h" ] || { echo "missing frida-gumjs.h" >&2; exit 65; }
[ -f "$GUM_DEVKIT/libfrida-gumjs.a" ] || { echo "missing libfrida-gumjs.a" >&2; exit 65; }

if [ "$(basename "$OUTPUT")" != "IOSUseFridaEngine.framework" ]; then
  echo "output must end in IOSUseFridaEngine.framework" >&2
  exit 64
fi
if [ -e "$OUTPUT" ] && [ "$REPLACE" != true ]; then
  echo "output exists; pass --replace to replace it" >&2
  exit 1
fi

SDK_PATH="$(xcrun --sdk macosx --show-sdk-path)"
TARGET="arm64-apple-ios17.0-macabi"
BUILD_TEMP="$(mktemp -d "${TMPDIR:-/tmp}/ios-use-frida-engine-build.XXXXXX")"
cleanup() { rm -rf "$BUILD_TEMP"; }
trap cleanup EXIT
xxd -i -n IOSUseFridaAgentSource \
  "$ROOT_DIR/playcover-frida-engine/IOSUseFridaAgent.js" \
  > "$BUILD_TEMP/IOSUseFridaAgent.generated.h"

# frida-gumjs.h is intentionally the official generated devkit header. It
# includes generated GLib/JSON/Gum headers, so retain both the source and
# build include roots rather than copying a reduced subset into this repo.
INCLUDES=(
  -I"$ROOT_DIR/playcover-frida-engine"
  -I"$BUILD_TEMP"
  -I"$GUM_DEVKIT"
  -I"$GUM_BUILD"
  -I"$SOURCE_ROOT"
  -I"$GUM_BUILD/bindings/gumjs"
  -I"$SOURCE_ROOT/bindings/gumjs"
  -I"$GUM_BUILD/bindings"
  -I"$SOURCE_ROOT/bindings"
  -I"$GUM_BUILD/gum"
  -I"$SOURCE_ROOT/gum"
  -I"$SOURCE_ROOT/gum/arch-arm64"
  -I"$SOURCE_ROOT/gum/backend-darwin/include"
  -I"$GUM_BUILD/subprojects/glib"
  -I"$SOURCE_ROOT/subprojects/glib"
  -I"$GUM_BUILD/subprojects/glib/glib"
  -I"$SOURCE_ROOT/subprojects/glib/glib"
  -I"$GUM_BUILD/subprojects/glib/gobject"
  -I"$SOURCE_ROOT/subprojects/glib/gobject"
  -I"$GUM_BUILD/subprojects/glib/gio"
  -I"$SOURCE_ROOT/subprojects/glib/gio"
  -I"$SOURCE_ROOT/subprojects/glib/gmodule"
  -I"$GUM_BUILD/subprojects/json-glib"
  -I"$SOURCE_ROOT/subprojects/json-glib"
  -I"$SOURCE_ROOT/subprojects/json-glib/json-glib"
  -I"$GUM_BUILD/subprojects/json-glib/json-glib"
  -I"$SOURCE_ROOT/subprojects/libffi"
  -I"$SOURCE_ROOT/subprojects/libffi/include"
  -I"$SOURCE_ROOT/subprojects/libffi/src/aarch64"
  -I"$SOURCE_ROOT/subprojects/quickjs"
  -I"$SOURCE_ROOT/subprojects/capstone/include"
  -I"$SOURCE_ROOT/subprojects/capstone/include/capstone"
)

clang -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror \
  -isysroot "$SDK_PATH" "${INCLUDES[@]}" \
  -c "$ROOT_DIR/playcover-frida-engine/IOSUseFridaEngine.m" \
  -o "$BUILD_TEMP/IOSUseFridaEngine.o"

clang -target "$TARGET" -fobjc-arc -Wall -Wextra -Werror \
  -isysroot "$SDK_PATH" -dynamiclib "$BUILD_TEMP/IOSUseFridaEngine.o" \
  -o "$BUILD_TEMP/IOSUseFridaEngine" \
  -L"$GUM_DEVKIT" -lfrida-gumjs \
  -framework Foundation -framework CoreFoundation -framework Security \
  -framework SystemConfiguration -lz -liconv -lresolv -lm \
  -install_name '@rpath/IOSUseFridaEngine.framework/IOSUseFridaEngine'

mkdir -p "$BUILD_TEMP/IOSUseFridaEngine.framework/Headers"
cp "$ROOT_DIR/playcover-frida-engine/IOSUseFridaEngine.h" \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Headers/"
cp "$BUILD_TEMP/IOSUseFridaEngine" \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/IOSUseFridaEngine"
plutil -create xml1 "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundleIdentifier -string io.ios-use.frida-engine \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundleName -string IOSUseFridaEngine \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundleExecutable -string IOSUseFridaEngine \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundlePackageType -string FMWK \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundleVersion -string 1 \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert CFBundleShortVersionString -string 16.5.6 \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert IOSUseFridaEngineABI -string "$ENGINE_ABI_REVISION" \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert IOSUseFridaAgentSHA256 -string "$AGENT_SHA256" \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"
plutil -insert IOSUseFridaSourceClosureSHA256 -string \
  "$ENGINE_SOURCE_CLOSURE_SHA256" \
  "$BUILD_TEMP/IOSUseFridaEngine.framework/Info.plist"

/usr/bin/codesign --force --sign - --timestamp=none \
  "$BUILD_TEMP/IOSUseFridaEngine.framework"
/usr/bin/codesign --verify --strict \
  "$BUILD_TEMP/IOSUseFridaEngine.framework"
file_output="$(file "$BUILD_TEMP/IOSUseFridaEngine.framework/IOSUseFridaEngine")"
if [[ "$file_output" != *"Mach-O 64-bit dynamically linked shared library arm64"* ]]; then
    echo "Engine is not arm64 Catalyst Mach-O" >&2; exit 65;
fi
nm_output="$(/usr/bin/nm -gU "$BUILD_TEMP/IOSUseFridaEngine.framework/IOSUseFridaEngine")"
if [[ "$nm_output" != *"_IOSUseFridaEngineCreate"* ]]; then
  echo "missing Engine ABI" >&2; exit 65;
fi
if [[ "$nm_output" != *"_IOSUseFridaEngineSetEventCallback"* ||
      "$nm_output" != *"_IOSUseFridaEngineClearEventCallback"* ]]; then
  echo "missing Frida event callback ABI" >&2; exit 65;
fi
if [[ "$nm_output" != *"_IOSUseFridaEngineEvaluate"* ]]; then
  echo "missing Engine ABI" >&2; exit 65;
fi

mkdir -p "$(dirname "$OUTPUT")"
if [ -e "$OUTPUT" ]; then
  rm -rf -- "$OUTPUT"
fi
mv "$BUILD_TEMP/IOSUseFridaEngine.framework" "$OUTPUT"
echo "Built $OUTPUT from Frida Gum $FRIDA_COMMIT"
