export const DEFAULT_PORT = 8100;
export const DEFAULT_DRIVER_HOST = '127.0.0.1';
export const CONNECT_TIMEOUT_MS = 10_000;
export const READ_TIMEOUT_MS = 45_000;
export const DRIVER_LAUNCH_MAX_WAIT_MS = 30_000;
export const DRIVER_LAUNCH_POLL_INTERVAL_MS = 500;
export const MAX_FRAME_SIZE_BYTES = 50 * 1024 * 1024;
export const CONNECTION_MAX_BUFFER_SIZE_BYTES = 64 * 1024 * 1024;
export const MAX_CAPTURE_SIZE_BYTES = 10 * 1024 * 1024;
export const MAX_DRIVER_LOG_BYTES = 10 * 1024 * 1024;
export const MILLISECONDS_PER_SECOND = 1_000;
export const PROCESS_INFO_TIMEOUT_MS = 5_000;
export const PROCESS_TERMINATE_TIMEOUT_MS = 5_000;
export const SOCKET_KEEPALIVE_INITIAL_DELAY_MS = 5_000;
export const USBMUX_REQUEST_TIMEOUT_MS = 5_000;
export const LOCKDOWN_PLIST_RECV_TIMEOUT_MS = 10_000;
export const LOCKDOWN_MAX_PLIST_SIZE_BYTES = 10 * 1024 * 1024;

export const DEVICE_DETECT_CACHE_TTL_MS = 5_000;
export const SIMULATOR_DETECT_RETRY_COUNT = 6;
export const SIMULATOR_DETECT_RETRY_SLEEP_SECONDS = '0.5';
export const SIMULATOR_BOOT_TIMEOUT_MS = 120_000;
export const SIMULATOR_TERMINATE_TIMEOUT_MS = 5_000;

export const FLOW_NSLOG_CONNECT_TIMEOUT_MS = 15_000;
export const FLOW_NSLOG_CONNECT_POLL_MS = 200;
export const FLOW_SHORT_SLEEP_THRESHOLD_MS = 200;
export const FLOW_DEFAULT_SLEEP_MS = 1_000;
export const FLOW_ABORT_CHECK_INTERVAL_MS = 500;
export const LOG_POLL_INTERVAL_MS = 300;
export const OSLOG_ABORT_POLL_INTERVAL_MS = 200;
export const DEFAULT_TARGET_RATIO = 0.5;

export const NSLOGGER_DEFAULT_PORT = 50_000;
export const NSLOGGER_DEFAULT_BUFFER_SIZE = 50_000;
export const NSLOGGER_MAX_RECV_BUFFER_BYTES = 1024 * 1024;
export const NSLOG_LOCK_STALE_MS = 60 * 60 * 1000;

export const OSLOG_BUFFER_MAX_LINES = 5_000;
export const OSLOG_DEFAULT_COLLECT_TIMEOUT_MS = 5_000;
export const OSLOG_DEFAULT_SIMULATOR_LAST_SEC = 10;

export const PROXY_MITMDUMP_PORT = 9080;
export const PROXY_PROCESS_GRACE_MS = 3_000;
export const PROXY_PROCESS_POLL_MS = 100;
export const PROXY_FORCED_KILL_DELAY_MS = 1_000;
export const PROXY_WAIT_PORT_POLL_MS = 200;
export const PROXY_LAN_PROBE_TIMEOUT_MS = 5_000;
export const PROXY_LAN_PROBE_POLL_MS = 300;
export const MITMPROXY_CA_GENERATION_TIMEOUT_MS = 10_000;
export const MITMPROXY_CA_GENERATION_POLL_MS = 200;
